CREATE DATABASE AIRLINE_DWH;

CREATE SCHEMA AIRLINE_DWH.RAW;       
CREATE SCHEMA AIRLINE_DWH.STAGING;   
CREATE SCHEMA AIRLINE_DWH.ANALYTICS; 
CREATE SCHEMA AIRLINE_DWH.AUDIT;     

CREATE WAREHOUSE ETL_WH WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;