CREATE OR REPLACE FILE FORMAT AIRLINE_DWH.RAW.CSV_FORMAT
    TYPE = 'CSV' 
    FIELD_DELIMITER = ',' 
    SKIP_HEADER = 1 
    NULL_IF = ('NULL', 'null', '') 
    EMPTY_FIELD_AS_NULL = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE; 