CREATE OR REPLACE PROCEDURE AIRLINE_DWH.RAW.LOAD_FLIGHTS_RAW()
RETURNS STRING LANGUAGE SQL AS
$$
DECLARE
  rows_inserted INT;
BEGIN
    COPY INTO AIRLINE_DWH.RAW.RAW_FLIGHTS
    FROM @AIRLINE_DWH.RAW.AIRLINE_STAGE
    FILE_FORMAT = (FORMAT_NAME = 'AIRLINE_DWH.RAW.CSV_FORMAT');

    rows_inserted := SQLROWCOUNT; 

    INSERT INTO AIRLINE_DWH.AUDIT.LOAD_LOGS (PROCEDURE_NAME, STEP_NAME, ROWS_AFFECTED, STATUS)
    VALUES ('LOAD_FLIGHTS_RAW', 'STAGE_TO_RAW', :rows_inserted, 'SUCCESS');

    COMMIT;
    RETURN 'Raw Load Successful, Rows: ' || :rows_inserted;
END;
$$;