CREATE OR REPLACE TABLE AIRLINE_DWH.AUDIT.LOAD_LOGS (
    LOG_ID INT IDENTITY(1,1),         
    PROCEDURE_NAME VARCHAR,           
    STEP_NAME VARCHAR,                
    ROWS_AFFECTED INT,                
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUS VARCHAR                    
);