CREATE OR REPLACE PROCEDURE AIRLINE_DWH.STAGING.LOAD_CLEAN_FLIGHTS()
RETURNS STRING LANGUAGE SQL AS
$$
DECLARE
  rows_inserted INT;
BEGIN
    INSERT INTO AIRLINE_DWH.STAGING.CLEAN_FLIGHTS (
        PASSENGER_ID, FULL_NAME, GENDER, AGE, NATIONALITY, DEPARTURE_DATE, FLIGHT_STATUS
    )
    SELECT 
        PASSENGER_ID,
        FIRST_NAME || ' ' || LAST_NAME,
        GENDER,
        TRY_CAST(AGE AS INT),
        NATIONALITY,
        TRY_TO_DATE(DEPARTURE_DATE, 'MM/DD/YYYY'),
        FLIGHT_STATUS
    FROM AIRLINE_DWH.RAW.STREAM_RAW_FLIGHTS
    WHERE METADATA$ACTION = 'INSERT';

    rows_inserted := SQLROWCOUNT;

    INSERT INTO AIRLINE_DWH.AUDIT.LOAD_LOGS (PROCEDURE_NAME, STEP_NAME, ROWS_AFFECTED, STATUS)
    VALUES ('LOAD_CLEAN_FLIGHTS', 'RAW_TO_STAGING', :rows_inserted, 'SUCCESS');

    COMMIT;
    RETURN 'Staging Load Successful, Rows: ' || :rows_inserted;
END;
$$;