CREATE OR REPLACE STREAM AIRLINE_DWH.RAW.STREAM_RAW_FLIGHTS 
ON TABLE AIRLINE_DWH.RAW.RAW_FLIGHTS;

CREATE OR REPLACE TABLE AIRLINE_DWH.STAGING.CLEAN_FLIGHTS (
    PASSENGER_ID VARCHAR,
    FULL_NAME VARCHAR,      
    GENDER VARCHAR,
    AGE INT,                
    NATIONALITY VARCHAR,
    DEPARTURE_DATE DATE,    
    FLIGHT_STATUS VARCHAR
);

CREATE OR REPLACE STREAM AIRLINE_DWH.STAGING.STREAM_CLEAN_FLIGHTS 
ON TABLE AIRLINE_DWH.STAGING.CLEAN_FLIGHTS;

CREATE OR REPLACE TABLE AIRLINE_DWH.ANALYTICS.FACT_FLIGHTS (
    PASSENGER_ID VARCHAR,
    FLIGHT_DATE DATE,
    STATUS VARCHAR,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() 
);

SHOW STREAMS IN DATABASE AIRLINE_DWH;