CREATE OR REPLACE PROCEDURE AIRLINE_DWH.ANALYTICS.LOAD_FACT_FLIGHTS()
RETURNS STRING LANGUAGE SQL AS
$$
DECLARE
  rows_inserted INT;
BEGIN
    INSERT INTO AIRLINE_DWH.ANALYTICS.FACT_FLIGHTS (PASSENGER_ID, FLIGHT_DATE, STATUS)
    SELECT PASSENGER_ID, DEPARTURE_DATE, FLIGHT_STATUS
    FROM AIRLINE_DWH.STAGING.STREAM_CLEAN_FLIGHTS
    WHERE METADATA$ACTION = 'INSERT';

    rows_inserted := SQLROWCOUNT;

    INSERT INTO AIRLINE_DWH.AUDIT.LOAD_LOGS (PROCEDURE_NAME, STEP_NAME, ROWS_AFFECTED, STATUS)
    VALUES ('LOAD_FACT_FLIGHTS', 'STAGING_TO_ANALYTICS', :rows_inserted, 'SUCCESS');

    COMMIT;
    RETURN 'Analytics Load Successful, Rows: ' || :rows_inserted;
END;
$$;