DELETE FROM AIRLINE_DWH.ANALYTICS.FACT_FLIGHTS;
SELECT COUNT(*) FROM AIRLINE_DWH.ANALYTICS.FACT_FLIGHTS;

SELECT COUNT(*) 
FROM AIRLINE_DWH.ANALYTICS.FACT_FLIGHTS 
AT(OFFSET => -60*5);

INSERT INTO AIRLINE_DWH.ANALYTICS.FACT_FLIGHTS
SELECT * FROM AIRLINE_DWH.ANALYTICS.FACT_FLIGHTS AT(OFFSET => -60*10);

DROP TABLE AIRLINE_DWH.ANALYTICS.FACT_FLIGHTS;
SELECT * FROM AIRLINE_DWH.ANALYTICS.FACT_FLIGHTS;

UNDROP TABLE AIRLINE_DWH.ANALYTICS.FACT_FLIGHTS;
SELECT COUNT(*) FROM AIRLINE_DWH.ANALYTICS.FACT_FLIGHTS;

